### ISSUE TITLE
[Documentation] Events.c documentation

### ISSUE THREAD

**Issue by DerekTBrown** [N0NB/hamlib#13]
On the following page:

http://hamlib.sourceforge.net/manuals/1.2.15/event_8c.html

The callback set methods are defined, but freq_cb_t, mode_cb_t, etc are not.

**Comment by N0NB** [comment]
* On 2016 14 Jan 10:13 -0600, Derek Brown wrote:
> On the following page:
> 
> http://hamlib.sourceforge.net/manuals/1.2.15/event_8c.html
> 
> The callback set methods are defined, but freq_cb_t, mode_cb_t, etc
> are not.

I'm not surprised as the Doxygen program reads comments embedded in the
source code and that was not always done completely.  More than likely
the same is true for the Doxygen generated 3.0.1 manual.

I am working on a manual and after cleaning up some other outstanding
documentation on the Wiki, I'll turn my attention to documenting the
function calls in it as best as I can.  Eventually the Doxygen generated
files will be deprecated.

- Nate

-- 

"The optimist proclaims that we live in the best of all
possible worlds.  The pessimist fears this is true."

Ham radio, Linux, bikes, and more: http://www.n0nb.us

**Comment by DerekTBrown** [comment]
That sounds awesome! Let me know if there is a way I can help out.  

I am currently working on an open source logging / radio control application ontop of HamLib.  I have a found a few such errors, and will likely make a pull request in the near future with some of these changes.  However, I want the current version to be compatible with existing versions of HamLib, so I am extending many of the classes in HamLib.
