### ISSUE TITLE
Feature request: Lua binding

### ISSUE THREAD

**Issue by kukabu** [N0NB/hamlib#27]
Hello

Lua is a powerful, embeddable scripting language and it would be great to add a binding.

**Comment by airween** [comment]
I'll see it soon (if nobody wants to try before :))

**Comment by kukabu** [comment]
Thank!

**Comment by airween** [comment]
Well, after a few nightmare, I've comitted the Lua bindings through SWIG for Hamlib:
https://github.com/airween/hamlib/tree/swig
Please review it, and let me know about your experiences.

73, Ervin

**Comment by kukabu** [comment]
Thank! I will test it.

**Comment by kukabu** [comment]
I checks basic functions it works for me. Thanks!
Also I found two small issues: https://gist.github.com/kukabu/7b6e0d0e7a33251cdac6eba6e0fba5f2

**Comment by airween** [comment]
Thanks for your feedback. I've modified the affected part of my code, and now I'll make a pull request to master.

**Comment by kukabu** [comment]
Thanks!!!
