### ISSUE TITLE
support for baofeng uv-3r, uv-5r

### ISSUE THREAD

**Issue by leite** [N0NB/hamlib#3]
Hi,

Nice project, I've been looking for support to baofeng radios, it'll be awesome!

thanks in advance!

**Comment by N0NB** [comment]
* On 2015 12 Jan 22:51 -0600, Francisco Leite wrote:
> Hi,
> 
> Nice project, I've been looking for support to baofeng radios, it'll
> be awesome!
> 
> thanks in advance!

Hi Francisco.

I would guess that the CHIRP project would probably meet your needs:

http://chirp.danplanet.com/projects/chirp/wiki/Home

73, Nate

-- 

"The optimist proclaims that we live in the best of all
possible worlds.  The pessimist fears this is true."

Ham radio, Linux, bikes, and more: http://www.n0nb.us

**Comment by mdblack98** [comment]
Can't this be closed?  Not applicable to hamlib

**Comment by N0NB** [comment]
Closing as OP has not replied to using CHIRP as an option and these are likely not supported radios in Hamlib.
