### ISSUE TITLE
FT897 and other drivers do not force the frequency cache to timeout after setting frequency

### ISSUE THREAD

**Issue by bergerspencer** [N0NB/hamlib#4]
See https://github.com/bergerspencer/hamlib/commit/e78e6d1d422e7e42637ef8c8cdd01269ed4eb72d for an example patch.

This is an issue in multiple drivers and probably should apply for setting things other than the frequency as well, so I did not create a pull request due to the scope of the issue.

Unlike the ft747 driver, the ft897, ft857, and probably more drivers do not make the cache timeout after setting frequency (among other things). So the frequency will be reported incorrectly when requested soon after setting it to something that rounds to a different 10Hz multiple.

This results in a bug when certain models are used in gpredict, see:
http://ehc.ac/p/gpredict/mailman/message/31445857/

The bug causes the frequency to drift because a dial change is percieved due to hamlib reading the frequency from the (now stale) cache. 

When doppler shifting, Gpredict sets the frequency, waits a small amount of time (1/10 of FT897_CACHE_TIMEOUT), and gets the frequency to account for differences in rig frequency precision. It later checks the frequency to see if the dial was turned, but because the original frequency was incorrect, it thinks the dial has changed whenever the doppler-shifted frequency crosses a 5Hz boundary.

**Comment by N0NB** [comment]
* On 2015 04 Feb 10:40 -0600, bergerspencer wrote:
> See
> https://github.com/bergerspencer/hamlib/commit/e78e6d1d422e7e42637ef8c8cdd01269ed4eb72d
> for an example patch.
> 
> This is an issue in multiple drivers and probably should apply for
> setting things other than the frequency as well, so I did not create a
> pull request due to the scope of the issue.
> 
> Unlike the ft747 driver, the ft897, ft857, and probably more drivers
> do not make the cache timeout after setting frequency (among other
> things). So the frequency will be reported incorrectly when requested
> soon after setting it to something that rounds to a different 10Hz
> multiple.
> 
> This results in a bug when certain models are used in gpredict, see:
> http://ehc.ac/p/gpredict/mailman/message/31445857/
> 
> The bug causes the frequency to drift because a dial change is
> percieved due to hamlib reading the frequency from the (now stale)
> cache.
> 
> When doppler shifting, Gpredict sets the frequency, waits a small
> amount of time (1/10 of FT897_CACHE_TIMEOUT), and gets the frequency
> to account for differences in rig frequency precision. It later checks
> the frequency to see if the dial was turned, but because the original
> frequency was incorrect, it thinks the dial has changed whenever the
> doppler-shifted frequency crosses a 5Hz boundary.

Hi.

If you think other models would benefit from the same patch, go ahead
and modify those backends and send me a pull request when you're ready.

73, Nate

-- 

"The optimist proclaims that we live in the best of all
possible worlds.  The pessimist fears this is true."

Ham radio, Linux, bikes, and more: http://www.n0nb.us
